- name: bluetooth - install dependencies
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
      - blueman

- name: bluetooth - ensure the service is enabled and started
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: true
