- name: Arch Linux
  hosts: local
  roles:
    - role: system
      vars:
        role_path: roles/arch

    - role: interface
      vars:
        role_path: roles/arch

    - role: packages
      vars:
        role_path: roles/arch
