---
- name: Media - install packages
  ansible.builtin.package:
    name:
      - krita
      - inkscape
      - spotify
      - aseprite
    state: present
  ignore_errors: true
  register: ignore_errors_register
