window = suppressevent maximize, class:.*
# window = forceinput, class:.*

# Browser
window = nodim, class:^(brave)$
window = nodim, class:^(firefox)$

# Bluetooth
$bluetooth = title:^(.*overskride.*)$
window = float, $bluetooth
window = size 26% 96%, $bluetooth
window = move 100%-w-2 50, $bluetooth

# Base Rules
$center-float = class:^(center-float)$|^(.*file-roller.*)$|^(.*FileRoller.*)$
$center-float-large = class:^(center-float-large)$|^(.*Geeqie.*)$|^(.*geeqie.*)$|^(.*celluloid.*)$|^(.*mpv.*)$
$center-float-title = title:^(.*Open Folder.*)$|^(.*Open File.*)$|^(.*Save File.*)$|^(.*Save Folder.*)$|^(.*Save Image.*)$|^(.*Save As.*)$|^(.*Open As.*)$
$center-float-mini = class:^(center-float-mini)$|^(.*galculator.*)$

window = float, $center-float-large
window = size 70% 70%, $center-float-large
window = center 1, $center-float-large

window = float, $center-float
window = float, $center-float-title
window = size 50% 50%, $center-float
window = size 50% 50%, $center-float-title
window = center 1, $center-float
window = center 1, $center-float-title

window = float, $center-float-mini
window = size 30% 40%, $center-float-mini
window = center 1, $center-float-mini

# Prevent going idle when on fullscreen
window = idleinhibit always, class:^(.*steam_app.*)$
window = fullscreen, class:^steam_app\d+$
window = idleinhibit fullscreen, class:^(.*celluloid.*)$|^(.*mpv.*)$
window = idleinhibit fullscreen, class:^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*Brave.*)$|^(.*firefox.*)$|^(.*chromium.*)$

window = fullscreen, class:^(dontstarve_steam)$

# Workspace Rules
# ---------------------------------

# 3D/Image
# window = workspace 5, class:^(.*pinta.*)$|(.*krita.*)$|(.*blender.*)$|(.*Upscayl.*)$

# Spotify
window = noinitialfocus, class:(.*Spotify.*)
window = workspace 8 silent, class:^(.*Spotify.*)$

# Slack
window = workspace 9 silent, class:^(.*Slack.*)$

# Obsidian
window = workspace 10 silent, class:^(.*obsidian.*)$

# PDF Viewer
$zathura = class:^(.*zathura.*)$
window = float, $zathura
window = size 35% 90%, $zathura
window = center 1, $zathura

# Float Rules
#window = float, xfce-polkit|wleave|title:branchdialog|nwg-look|nm-connection-editor

# Clipse
window = float, class:(clipse)
window = size 1200 800, class:(clipse)

# Scratchpads
$scratchpad-large = class:^(scratchpad-large)$
window = float, $scratchpad-large
window = center 1, $scratchpad-large
window = size 70% 70%, $scratchpad-large
window = animation slide, $scratchpad-large
window = workspace special:scratchpad-large silent, $scratchpad-large

$scratchpad = class:^(scratchpad)$
window = float, $scratchpad
window = center 1, $scratchpad
window = size 50% 50%, $scratchpad
window = animation slide, $scratchpad
window = workspace special:scratchpad silent, $scratchpad

#$scratchpad-mini = class:^(scratchpad-mini)$
window = float, $scratchpad-mini
window = center 1, $scratchpad-mini
window = size 30% 40%, $scratchpad-mini
window = animation slide, $scratchpad-mini
window = workspace special:scratchpad-mini silent, $scratchpad-mini

$sideScratchpad = class:^(.*pavucontrol.*)$|(.*blueman-manager.*)$|^(.*localsend.*)$
window = workspace special:scratchpad silent, $sideScratchpad
window = size 30% 90%, $sideScratchpad
window = float, $sideScratchpad
window = center 1, $sideScratchpad

# Layer rules
# ---------------------------------

# Launcher
layer = noanim, ags_launcher

# Notification
layer = noanim, ags_notifications

# Bar
layer = blur, ags_bar
layer = ignorezero, ags_bar
