- name: Arch Linux Setup
  hosts: local

- name: Arch Playbook
  ansible.builtin.include_playbook: ./arch/main.yml

- name: Development Playbook
  ansible.builtin.include_playbook: ./development/main.yml

- name: Apps Playbook
  ansible.builtin.include_playbook: ./apps/main.yml
