- name: Arch Linux Setup
  hosts: localhost
- import_playbook: ./arch/system/main.yml
# - import_playbook: ./arch/interface/main.yml
# - import_playbook: ./arch/packages/main.yml
- import_playbook: ./common/main.yml
