- name: Arch Linux Setup
  hosts: local
  connection: local
  tasks:
    - name: Fetch user's home directory
      ansible.builtin.getent:
        database: passwd
        key: "{{ ansible_user_id }}"
      register: passwd_entry

    - name: Debug home directory
      debug:
        msg: "User's home directory is {{ passwd_entry.entries.0.home }}"

# - name: Arch Playbook
#   ansible.builtin.import_playbook: ./arch/main.yml
#
# - name: Development Playbook
#   ansible.builtin.import_playbook: ./development/main.yml

# - name: Apps Playbook
#   ansible.builtin.import_playbook: ./apps/main.yml
