- name: Arch Playbook
  hosts: local
  ansible.builtin.import_playbook: ./arch/main.yml

- name: Development Playbook
  hosts: local
  ansible.builtin.import_playbook: ./development/main.yml

- name: Apps Playbook
  hosts: local
  ansible.builtin.import_playbook: ./apps/main.yml
