- name: Arch Linux Setup
  hosts: local
  connection: local
  vars_files: ./vars/all.yml

- name: Arch System Playbook
  ansible.builtin.import_playbook: ./arch/system/main.yml

- name: Arch Interface Playbook
  ansible.builtin.import_playbook: ./arch/interface/main.yml

- name: Development Playbook
  ansible.builtin.import_playbook: ./development/main.yml

- name: Apps Playbook
  ansible.builtin.import_playbook: ./apps/main.yml
