---
- name: MacOS Setup
  hosts: local
  connection: local

- name: System Playbook
  ansible.builtin.import_playbook: ./macos/system/main.yml

- name: Development Playbook
  ansible.builtin.import_playbook: ./macos/development/main.yml

- name: Apps Playbook
  ansible.builtin.import_playbook: ./macos/apps/main.yml
