---
collections:
  - name: community.general
    source: https://galaxy.ansible.com

  - name: community.crypto
    source: https://galaxy.ansible.com

  - name: ansible.posix
    source: https://galaxy.ansible.com

  - name: kewlfft.aur
    source: https://galaxy.ansible.com
