---
- name: IDEs - install
  ansible.builtin.package:
    name:
      - neovim
      - helix
      - tidy-html5
      - luarocks
      - dotenv-linter
    state: present
  ignore_errors: true
  register: ignore_errors_register

- name: Nvim setup
  ansible.builtin.import_tasks: ./config/nvim.yml

- name: Helix setup
  ansible.builtin.import_tasks: ./config/helix.yml
