- name: tmux - create config directory
  file:
    path: ~/.config/tmux
    state: directory

- name: tmux - symlink files
  file:
    src: "{{ ansible_env.PWD }}/provision/common/roles/tmux/files/{{ item }}"
    path: "~/.config/tmux/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - .tmux.conf
