- name: Ags - install
  become: true
  kewlfft.aur.aur:
    use: yay
    name:
      - aylurs-gtk-shell
      - libdbusmenu-gtk3
    state: present
  notify: Rkhunter propupdate
  ignore_errors: true
  register: ignore_errors_register

- name: AGS - clone config from repo
  ansible.builtin.git:
    repo: "git@github.com:vicentelyrio/ags-desktop.git"
    dest: "~/.config/ags"
    clone: true
    version: main
  ignore_errors: true
  register: ignore_errors_register
