- name: Ags - install
  become: true
  kewlfft.aur.aur:
    use: yay
    name:
      - aylurs-gtk-shell
    state: present
  notify: Rkhunter propupdate
  ignore_errors: true
  register: ignore_errors_register

