---
- name: Brightness - install
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - brightnessctl
      - ddcutil

- name: Brightness - build aur package (ddcci-driver-linux-dkms-git)
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: ddcci-driver-linux-dkms-git
    state: present
    extra_args: --builddir /tmp/aur-build --nobuild
  register: ddcci_build_result
  failed_when: false
  ignore_errors: true

- name: Brightness - install built DKMS package with pacman
  become: true
  become_user: root
  ansible.builtin.shell: |
    cd /home/{{ user.name }}/.cache/yay/ddcci-driver-linux-dkms-git/
    pacman -U --noconfirm *.pkg.tar*
  args:
    executable: /bin/bash
  when: ddcci_build_result is defined and ddcci_build_result.failed | default(false)
  register: ddcci_install_result
  failed_when: false
  changed_when: ddcci_install_result.rc | default(1) == 0

- name: Brightness - install light from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: light
    state: present
  register: light_install_result
  failed_when: false
  ignore_errors: true

# LIGHT Permission
- name: Brightness - copy rules for light run without sudo
  become: true
  become_user: root
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/system-brightness/files/90-backlight.rules"
    dest: /etc/udev/rules.d/
    mode: "0644"

# I2C DEV
- name: Brightness - enable i2c_dev
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    regexp: "i2c_dev"
    line: "i2c_dev"
    state: present
    create: true
    mode: "0644"
  when: system.external_display | bool

- name: Brightness - Ensure group i2c exists
  become: true
  become_user: root
  ansible.builtin.group:
    name: "i2c"
    state: present
  when: system.external_display | bool

- name: Brightness - Ensure the user is part of the i2c group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups:
      - i2c
    append: true
  when:
    - user.name is defined
    - system.external_display | bool

# DDCI
- name: Brightness - load DDCCI module
  become: true
  become_user: root
  community.general.modprobe:
    name: ddcci
    state: present
  when: system.external_display | bool
  failed_when: false

- name: Brightness - enable DDCCI
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    regexp: "ddcci"
    line: "ddcci"
    state: present
    create: true
    mode: "0644"
  when: system.external_display | bool

- name: Brightness - copy script
  become: true
  become_user: root
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/system-brightness/files/backlight-start.sh"
    dest: /usr/sbin/
    mode: "0755"
  when: system.external_display | bool

- name: Brightness - copy ddcci.service
  become: true
  become_user: root
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/system-brightness/files/ddcci.service"
    dest: /etc/systemd/system/
    mode: "0644"
  when: system.external_display | bool
  register: ddcci_service_unit

- name: Brightness - start ddcci.service
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: ddcci.service
    state: started
    enabled: true
    daemon_reload: "{{ ddcci_service_unit.changed | default(false) }}"
  when: system.external_display | bool
  failed_when: false
