- name: Wezterm - create config directory
  ansible.builtin.file:
    path: ~/.config/wezterm
    state: directory
    mode: "0600"

- name: Wezterm - symlink files
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/provision/common/roles/terminals/files/wezterm/{{ item }}"
    path: "~/.config/wezterm/{{ item }}"
    state: link
    follow: false
    force: "yes"
  loop:
    - wezterm.lua
