- name: Ensure group user.group exists
  ansible.builtin.group:
    name: "{{ user.group }}"
    state: present
  when: user.name is defined

- name: Ensure the user user.name exists
  become: true
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    groups:
      - "{{ user.group }}"
      - wheel
      - network
      - lock
      - uucp
    append: true
    system: false
    createhome: true
    home: /home/{{ user.name }}
  when: user.name is defined
