- name: Alacritty - create config directory
  ansible.builtin.file:
    path: ~/.config/alacritty
    state: directory
    mode: "0644"

- name: Alacritty - symlink files
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminals/files/alacritty/{{ item }}"
    dest: "~/.config/alacritty/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - alacritty.yml
    - colors.yml
    - fonts.yml
    - keybinds.yml
