- name: Alacritty - create config directory
  ansible.builtin.file:
    path: ~/.config/alacritty
    state: directory
    mode: "0755"

- name: Alacritty - symlink files
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminals/files/alacritty/{{ item }}"
    dest: ~/.config/alacritty/{{ item }}
    state: link
    follow: false
    force: true
  loop:
    - alacritty.yml
    - colors.yml
    - fonts.yml
    - keybinds.yml
