- name: Wezterm - create config directory
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/wezterm
    state: directory
    mode: "0644"

- name: Wezterm - symlink files
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminals/files/wezterm/{{ item }}"
    dest: "~/.config/wezterm/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - wezterm.lua
