---
- name: Wezterm - create config directory
  ansible.builtin.file:
    path: ~/.config/wezterm
    state: directory
    mode: "0600"

- name: Wezterm - symlink files
  ansible.builtin.file:
    src: "{{ playbook_dir }}/development/roles/terminals/files/wezterm/{{ item }}"
    path: ~/.config/wezterm/{{ item }}
    state: link
    follow: false
    force: true
  loop:
    - wezterm.lua
