---
- name: Pacseek - install manager
  kewlfft.aur.aur:
    use: yay
    name:
      - pacseek
    state: present
  notify: Rkhunter propupdate
  ignore_errors: true
  register: ignore_errors_register
  become: true
  become_user: aur_builder
