# - name: Github - install git-cli
#   become: true
#   kewlfft.aur.aur:
#     use: yay
#     name:
#       - github-cli-git
#     state: present

- include_tasks: ./default-user.yml
- include_tasks: ./options.yml
- include_tasks: ./other-users.yml
