# - name: Github - install git-cli
#   become: true
#   kewlfft.aur.aur:
#     use: yay
#     name:
#       - github-cli-git
#     state: present

- name: Github - Create Default User
  ansible.builtin.include_tasks: ./default-user.yml

- name: Github - Create Options
  ansible.builtin.include_tasks: ./options.yml

- name: Github - Create Aditional Users
  ansible.builtin.include_tasks: ./other-users.yml
