- name: Github - update gitconfig file
  ansible.builtin.blockinfile:
    block: "{{ lookup('template', '../templates/gitconfig-main.j2') }}"
    dest: ~/.gitconfig
    mode: "0644"
    marker: "# {mark} custom github users"
    prepend_newline: true
    create: true
  when: git.users is defined

- name: Github - create scoped gitconfig
  ansible.builtin.template:
    src: ../templates/gitconfig-scoped.j2
    dest: "~/.gitconfig-{{ item.scope }}"
    mode: "0777"
  with_items: "{{ git.users }}"
  when: git.users is defined

- name: Github - create aditional user ssh keypair
  community.crypto.openssh_keypair:
    force: false
    state: present
    type: ed25519
    mode: "0400"
    path: "~/.ssh/id_ssh_{{ item.scope }}"
    comment: "{{ item.email }}"
  with_items: "{{ git.users }}"
  when: git.users is defined


- name: Github - create default user ssh config
  community.general.git_config:
    name: core.sshCommand
    value: "~/.ssh/id_ssh_default"
    scope: global
    state: present
  when: git.default is defined

- name: Github - create ssh config for aditional user
  community.general.git_config:
    name: core.sshCommand
    value: "~/.ssh/id_ssh_{{ item.scope }}"
    file: "~/.gitconfig-{{ item.scope }}"
    state: present
    scope: global
  with_items: "{{ git.users }}"
  when: git.users is defined

- name: Github - add aditional user key to agent
  ansible.builtin.shell: "ssh-add ~/.ssh/id_ssh_{{ item.scope }}"
  args:
    executable: /bin/bash
  with_items: "{{ git.users }}"
  when: git.users is defined
  register: output
  changed_when: output.rc != 0

- name: Github - update config file with scoped user
  ansible.builtin.blockinfile:
    block: "{{ lookup('template', '../templates/config-scoped.j2') }}"
    dest: ~/.ssh/config
    mode: "0644"
    marker: "# {mark} custom github hosts"
    prepend_newline: true
    create: true
  when: git.users is defined

