---
- name: Yay - Install
  kewlfft.aur.aur:
    name: yay
    state: present
  become: true
  become_user: aur_builder

- name: Yay - Install aur hooks
  kewlfft.aur.aur:
    use: yay
    name:
      - check-broken-packages-pacman-hook-git
      - reflector-pacman-hook-git
      - sync-pacman-hook-git
      - needrestart
      - paccache-hook
    state: present
  become: true
  become_user: aur_builder

