- name: Node - install nvm
  become: true
  kewlfft.aur.aur:
    use: yay
    name:
      - nvm
    state: present
  notify: Rkhunter propupdate

- name: Node - install node and set version
  ansible.builtin.shell: "source /root/.nvm/nvm.sh && nvm install node"
  args:
    executable: /bin/bash
  register: output
  changed_when: output.rc != 0

- name: Node - install yarn
  ansible.builtin.shell: "npm i -g yarn && corepack enable"
  args:
    executable: /bin/bash
  register: output
  changed_when: output.rc != 0
