- name: Helix - create config directory
  ansible.builtin.file:
    path: ~/.config/helix
    state: directory
    mode: "0600"

- name: Helix - symlink files
  ansible.builtin.file:
    src: "{{ playbook_dir }}/development/roles/ides/files/helix/{{ item }}"
    path: ~/.config/helix/{{ item }}
    state: link
    follow: false
    force: "yes"
  loop:
    - config.toml
