- name: Clone Neovim config from my repo
  ansible.builtin.git:
    repo: https://github.com/vicentelyrio/nvim.git
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    force: true
    clone: true
    update: true
