- name: Neovim - create config directory
  ansible.builtin.file:
    path: "{{ home_dir_result.stdout }}/.config/nvim"
    state: directory
    mode: "0644"

- name: Neovim - clone config from my repo
  ansible.builtin.git:
    repo: "https://github.com/vicentelyrio/nvim.git"
    dest: "{{ home_dir_result.stdout }}/.config/nvim"
    clone: true
    version: main
