- name: Neovim - create config directory
  ansible.builtin.file:
    path: "~/.config/nvim"
    state: directory
    mode: "0777"

- name: Neovim - clone config from my repo
  become: true
  ansible.builtin.git:
    repo: "https://github.com/vicentelyrio/nvim.git"
    dest: "/home/{{ user.name }}/.config/nvim"
    clone: true
    version: main
