- name: Hyprland - install
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - hyprland
      - hyprpaper
      - hypridle
      - xdg-desktop-portal-hyprland
      - qt5-wayland
      - qt6-wayland
    state: present
  notify: Rkhunter propupdate

- name: Hyprland - install aur packages
  become: true
  kewlfft.aur.aur:
    use: yay
    name:
      - hyprprop-git
      - hyprpicker
      - hyprlock
    state: present
  notify: Rkhunter propupdate

- name: Hyprland - create config directory
  ansible.builtin.file:
    path: ~/.config/hypr
    state: directory
    mode: "0777"

- name: Hyprland - copy files
  ansible.posix.synchronize:
    src: ../files/hypr/
    dest: "/home/{{ user.name }}/.config/hypr/"
    recursive: true
  delegate_to: localhost
