- name: Hyprland - install
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - hyprland
      - hyprpaper
      - hypridle
      - xdg-desktop-portal-hyprland
      - qt5-wayland
      - qt6-wayland
    state: present
  notify: Rkhunter propupdate

- name: Hyprland - install aur packages
  become: true
  kewlfft.aur.aur:
    use: yay
    name:
      - hyprprop-git
      - hyprpicker
      - hyprlock
      - pyprland
      # Theme
      - catppuccin-gtk-theme-macchiato
      - catppuccin-cursors-macchiato
      - ttf-ms-win11-auto
    state: present
  notify: Rkhunter propupdate

- name: Hyprland - create main config directory
  ansible.builtin.file:
    path: ~/.config/hypr
    state: directory
    mode: "0777"

- name: Hyprland - create config directory
  ansible.builtin.file:
    path: ~/.config/hypr/config
    state: directory
    mode: "0777"

- name: Hyprland - create scripts directory
  ansible.builtin.file:
    path: ~/.config/hypr/theme
    state: directory
    mode: "0777"

- name: Hyprland - create theme directory
  ansible.builtin.file:
    path: ~/.config/hypr/theme
    state: directory
    mode: "0777"

- name: Hyprland - copy files
  ansible.posix.synchronize:
    src: ../files/hypr/
    dest: "/home/{{ user.name }}/.config/hypr/"
    recursive: true
  delegate_to: localhost
