- name: Hyprland - install
  ansible.builtin.package:
    name:
      - hyprland
      - hyprprop-git
      - hyprpaper
      - hyprpicker
      - hyprlock
      - hypridle
      - xdg-desktop-portal-hyprland
      - qt4-wayland
      - qt5-wayland
      - qt6-wayland
    state: present
  register: install
  until: install is success
  retries: 10
  delay: 2
  notify: rkhunter propupdate

- name: Hyprland - copy files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/hyprland/files/hypr"
    dest: "~/.config"
    mode: "0644"
    owner: "{{ user.name }}"
