- name: Hyprland - install
  become: true
  ansible.builtin.package:
    name:
      - hyprland
      - hyprpaper
      - hypridle
      - xdg-desktop-portal-hyprland
      - qt4-wayland
      - qt5-wayland
      - qt6-wayland
      # - hyprprop-git
      # - hyprpicker
      # - hyprlock
    state: present
  notify: Rkhunter propupdate

- name: Hyprland - install aur packages
  become: true
  ansible.builtin.yay:
    name:
      - hyprprop-git
      - hyprpicker
      - hyprlock
    state: present
  notify: Rkhunter propupdate

- name: Hyprland - copy files
  become: true
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/hyprland/files/hypr"
    dest: "~/.config"
    mode: "0644"
    owner: "{{ user.name }}"
