---
- name: Development Roles
  hosts: local
  vars_files: ../../vars/all.yml
  ignore_errors: true
  roles:
    - github
    - terminals
    - terminal
    - ides
    - node
    - herdr
    - db
    - docker
    - code
