- name: Install microcode updates for intel (if necessary)
  become: true
  become_user: true
  ansible.builtin.package:
    name: intel-ucode
    state: present
  notify:
    - Grub - update
  when: system.processor == "intel"

- name: Install microcode updates for amd (if necessary)
  become: true
  become_user: true
  ansible.builtin.package:
    name: amd-ucode
    state: present
  notify:
    - Grub - update
  when: system.processor == "amd"
