- name: Ensure aur_builder user exists
  ansible.builtin.user:
    name: aur_builder
    shell: /bin/bash
    create_home: yes

- name: Allow aur_builder to run pacman without password
  ansible.builtin.copy:
    dest: /etc/sudoers.d/aur_builder
    content: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman\n"
    mode: '0440'
