---
- name: Ensure aur_builder user exists
  ansible.builtin.user:
    name: aur_builder
    shell: /bin/bash
    create_home: yes
  become: true
  become_user: root

- name: Allow aur_builder to run pacman without password and disable requiretty
  ansible.builtin.copy:
    dest: /etc/sudoers.d/aur_builder
    content: |
      Defaults:aur_builder !requiretty
      aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman
    mode: '0440'
    owner: root
    group: root
  become: true
  become_user: root
