[pyprland]
plugins = ["scratchpads", "expose", "magnify"]

[scratchpads.terminal]
command = "alacritty --class scratchpad-large"
excludes = ["dots", "yazi"]
lazy = true

[scratchpads.yazi]
command = "alacritty --class scratchpad-large -e zsh -c 'yazi'"
lazy = true

[scratchpads.dots]
command = "alacritty --class scratchpad-large -e zsh -c 'gitui'"
excludes = ["terminal"]
lazy = true

[scratchpads.gtop]
command = "alacritty --class scratchpad-large -e zsh -c 'gtop'"
lazy = true
