---
- name: Television - install
  ansible.builtin.package:
    name:
      - television
    state: present
  ignore_errors: true
  register: ignore_errors_register

- name: Television - update channels
  ansible.builtin.command: tv update-channels
  changed_when: false

- name: Television - symlink channel overrides
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/television/files/cable/{{ item }}"
    dest: "~/.config/television/cable/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - files.toml
    - git-files.toml
    - git-diff.toml
    - recent-files.toml
    - dotfiles.toml
    - text.toml
    - todo-comments.toml

- name: Television - add shell integration to zshrc
  ansible.builtin.lineinfile:
    path: "~/.zshrc"
    line: 'eval "$(tv init zsh)"'
    create: true
    insertafter: EOF
