- name: Dependencies - install
  become: true
  ansible.builtin.package:
    update_cache: "yes"
    name:
      - python-pip
      - python-pexpect
      - base-devel
      - openssh
      - curl
      - git
      - rsync
      - coreutils
      - dateutils
      - lsof
      - cronie
      - rkhunter
      - nmap
