- name: BASH - symlink config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminal/files/bash/{{ item }}"
    path: ~/{{ item }}
    state: link
    follow: false
    force: true
  loop:
    - .bashrc
