- name: BASH - symlink config
  become: true
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminal/files/bash/{{ item }}"
    dest: "/home/{{ user.name }}/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - .bashrc
