---
- name: BASH - symlink config
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/provision/common/roles/terminal/files/bash/{{ item }}"
    path: ~/{{ item }}
    state: link
    follow: false
    force: true
  loop:
    - .bashrc
