- name: BASH - symlink config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminal/files/bash/{{ item }}"
    dest: "{{ home_dir_result.stdout }}/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - .bashrc
