- name: Bat - create config directory
  ansible.builtin.file:
    path: "~/.config/bat"
    state: directory
    mode: "0777"

- name: Bat - symlink config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminal/files/bat/{{ item }}"
    dest: "~/.config/bat/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - config

- name: Bat - create theme directory
  ansible.builtin.file:
    path: "~/.config/bat/themes"
    state: directory
    mode: "0777"

- name: Bat - download custom theme
  ansible.builtin.command: wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Macchiato.tmTheme

- name: Bat - rebuild cache
  ansible.builtin.command: bat cache --build

