- name: Bat - create config directory
  ansible.builtin.file:
    path: ~/.config/bat
    state: directory
    mode: "0755"

- name: Bat - symlink config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminal/files/bat/{{ item }}"
    dest: ~/.config/bat/{{ item }}
    state: link
    follow: false
    force: true
    owner: "{{ user.name }}"
  loop:
    - config

- name: Bat - create theme directory
  ansible.builtin.file:
    path: ~/.config/bat/themes
    state: directory
    mode: "0755"

- name: Bat - symlink themes
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminal/files/bat/themes/{{ item }}"
    dest: ~/.config/bat/themes/{{ item }}
    state: link
    follow: false
    force: true
    owner: "{{ user.name }}"
  loop:
    - Catppuccin-frappe.tmTheme
    - Catppuccin-latte.tmTheme
    - Catppuccin-macchiato.tmTheme
    - Catppuccin-mocha.tmTheme
