---
- name: Starship - create config directory
  ansible.builtin.file:
    path: "~/.config/starship"
    state: directory
    mode: "0777"

- name: Starship - symlink files
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminal/files/starship/{{ item }}"
    dest: "~/.config/starship/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - starship.toml
