---
- name: Terminal utilities - install
  become: true
  ansible.builtin.package:
    name:
      - ack
      - bat
      - bash-completion
      - eza
      - fzf
      - gitui
      - gtop
      - neofetch
      - starship
      - tmux
      - tree
      - zoxide
      - zsh
    state: present
