- name: Terminal utilities - install
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - ack
      - bat
      - bash-completion
      - eza
      - fzf
      - gitui
      - gtop
      - neofetch
      - starship
      - tmux
      - tree
      - zoxide
      - zsh
    state: present

- name: Bash
  ansible.builtin.import_tasks: ./config/bash.yml

- name: Zsh
  ansible.builtin.import_tasks: ./config/zsh.yml

- name: Fzf
  ansible.builtin.import_tasks: ./config/fzf.yml

- name: Starship
  ansible.builtin.import_tasks: ./config/starship.yml

- name: Tmux
  ansible.builtin.import_tasks: ./config/tmux.yml

- name: Gitui
  ansible.builtin.import_tasks: ./config/gitui.yml

- name: Bat
  ansible.builtin.import_tasks: ./config/bat.yml
