---
- name: Greeter - install
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - greetd

- name: Greeter - enable and start
  become: true
  become_user: root
  ansible.builtin.service:
    name: greetd
    enabled: true
    state: stopped

- name: Greeter - symlink files
  become: true
  become_user: root
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/system-greetd/files/{{ item }}"
    dest: "/etc/greetd/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - config.toml
    - hyprland.conf
    - start-hypr.sh
    - start-session.sh
