---
- name: IDEs - install
  ansible.builtin.package:
    name:
      - tidy
      - luarocks
      - neovim
      - helix
    state: present
  become: true
  become_user: root

- name: IDEs - Install aur packages
  kewlfft.aur.aur:
    use: yay
    name:
      - dotenv-linter-bin
      - cursor-bin
  become: true
  become_user: aur_builder

- name: Nvim setup
  ansible.builtin.import_tasks: ./config/nvim.yml

- name: Helix setup
  ansible.builtin.import_tasks: ./config/helix.yml
