- name: Bluetooth - install dependencies
  become: true
  become_user: true
  ansible.builtin.package:
    name:
      - bluez
      - bluez-utils
      - blueman

- name: Bluetooth - ensure the service is enabled and started
  become: true
  become_user: root
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: true
