- name: Bluetooth - install dependencies
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - bluez
      - bluez-utils
      - blueman
      - gnome-bluetooth-3.0
    state: present

- name: Bluetooth - ensure the service is enabled and started
  become: true
  become_user: root
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: true

- name: Bluetooth - Config experimental flag
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    create: true
    path: /etc/bluetooth/main.conf
    regexp: "#Experimental = false"
    line: "Experimental = true"

