- name: Bluetooth - install dependencies
  become: true
  ansible.builtin.package:
    name:
      - bluez
      - bluez-utils
      - blueman
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Bluetooth - ensure the service is enabled and started
  become: true
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: true
