- name: Network - install tools
  become: true
  ansible.builtin.package:
    name:
      - ethtool
      - wpa_supplicant
      - netctl
      - dhcpcd
      - nmap
      - networkmanager
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - Rkhunter propupdate

- name: Network - enable dhcp service
  ansible.builtin.service:
    name: dhcpcd
    state: started
    enabled: true

- name: Network - enable NetworkManager service
  become: true
  ansible.builtin.service:
    name: NetworkManager
    state: started
    enabled: true
