# ZSH
- name: ZSH - create config directory
  ansible.builtin.file:
    path: ~/.config/.zsh
    state: directory
    mode: "0600"

- name: ZSH - symlink files
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/provision/common/roles/terminal/files/{{ item }}"
    path: "~/.config/.zsh/{{ item }}"
    state: link
    follow: false
    force: "yes"
  loop:
    - .zshrc
    - .zshaliases

# FZF
- name: FZF - create config directory
  ansible.builtin.file:
    path: ~/.config/fzf
    state: directory
    mode: "0600"

- name: FZF - symlink files
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/provision/common/roles/terminal/files/{{ item }}"
    path: "~/.config/fzf/{{ item }}"
    state: link
    follow: false
    force: "yes"
  loop:
    - .fzf.zsh

# STARSHIP
- name: Starship - create config directory
  ansible.builtin.file:
    path: ~/.configstarship/
    state: directory
    mode: "0600"

- name: Starship - symlink files
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/provision/common/roles/terminal/files/{{ item }}"
    path: "~/.config/starship/{{ item }}"
    state: link
    follow: false
    force: "yes"
  loop:
    - starship.toml

# TMUX
- name: Tmux - create config directory
  ansible.builtin.file:
    path: ~/.config/tmux
    state: directory
    mode: "0600"

- name: Tmux - symlink files
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/provision/common/roles/terminal/files/{{ item }}"
    path: "~/.config/tmux/{{ item }}"
    state: link
    follow: false
    force: "yes"
  loop:
    - .tmux.conf
