- name: alacritty - create config directory
  file:
    path: ~/.config/alacritty
    state: directory

- name: alacritty - symlink files
  file:
    src: "{{ ansible_env.PWD }}/provision/common/roles/alacritty/files/{{ item }}"
    path: "~/.config/alacritty/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - alacritty.yml
    - colors.yml
    - fonts.yml
    - keybinds.yml
