---
- name: Bluetooth - install dependencies
  ansible.builtin.package:
    name:
      - bluez
      - bluez-utils
      - bluez-tools
      - bluez-obex
      - bluez-hid2hci
      - blueman
      - gnome-bluetooth-3.0
    state: present
  become: true
  become_user: root

- name: Bluetooth - install gui
  kewlfft.aur.aur:
    use: yay
    name:
      - overskride
      - solaar
    state: present
  become: true
  become_user: aur_builder

- name: Bluetooth - ensure the service is enabled and started
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: true
  become: true
  become_user: root

- name: Bluetooth - Config experimental flag
  ansible.builtin.lineinfile:
    create: true
    path: /etc/bluetooth/main.conf
    regexp: "#Experimental = false"
    line: "Experimental = true"
    mode: "0644"
  become: true
  become_user: root
