user:
  name: vicentelyrio
  group: users
  shell: /bin/zsh

system:
  locale: en
  timezone: America/Sao_Paulo
  processor: intel
  graphics_card: amd

bootloader: grub

ssh:
  port: 22
  enable_sshd: true
