- name: Pacman
  ansible.builtin.import_tasks: ./pacman

- name: Yay
  ansible.builtin.import_tasks: ./yay

- name: Gpu
  ansible.builtin.import_tasks: ./gpu

- name: Users
  ansible.builtin.import_tasks: ./user

- name: Locale
  ansible.builtin.import_tasks: ./locale

- name: Time
  ansible.builtin.import_tasks: ./time

- name: Cronie
  ansible.builtin.import_tasks: ./cronie

- name: Ssh
  ansible.builtin.import_tasks: ./ssh

- name: Grub
  ansible.builtin.import_tasks: ./grub
  tags: ['grub']

- name: Network
  ansible.builtin.import_tasks: ./network

- name: Bluetooth
  ansible.builtin.import_tasks: ./bluetooth

- name: Audio
  ansible.builtin.import_tasks: ./audio
