- name: Pacman
  ansible.builtin.import_tasks: ./pacman

- name: Yay
  ansible.builtin.import_tasks: ./yay

- name: Gpu
  ansible.builtin.import_tasks: ./gpu
  tags: ['gpu']

- name: Users
  ansible.builtin.import_tasks: ./user
  tags: ['users']

- name: Locale
  ansible.builtin.import_tasks: ./locale
  tags: ['locale']

- name: Time
  ansible.builtin.import_tasks: ./time
  tags: ['time']

- name: Cronie
  ansible.builtin.import_tasks: ./cronie

- name: Grub
  ansible.builtin.import_tasks: ./grub
  tags: ['grub']

- name: Network
  ansible.builtin.import_tasks: ./network
  tags: ['network']

- name: Bluetooth
  ansible.builtin.import_tasks: ./bluetooth
  tags: ['bluetooth']

- name: Audio
  ansible.builtin.import_tasks: ./audio
  tags: ['audio']

