[colors]
background       = '#24273A'
foreground       = '#CAD3F5'
dim-foreground   = '#CAD3F5'
light-foreground = '#CAD3F5'
cursor           = '#F4DBD6'

black            = '#494D64'
blue             = '#8AADF4'
cyan             = '#8BD5CA'
green            = '#A6DA95'
magenta          = '#F5BDE6'
red              = '#ED8796'
white            = '#CAD3F5'
yellow           = '#EED49F'

dim-black        = '#494D64'
dim-blue         = '#8AADF4'
dim-cyan         = '#8BD5CA'
dim-green        = '#A6DA95'
dim-magenta      = '#F5BDE6'
dim-red          = '#ED8796'
dim-white        = '#B8C0E0'
dim-yellow       = '#EED49F'

light-black      = '#5B6078'
light-blue       = '#8AADF4'
light-cyan       = '#8BD5CA'
light-green      = '#A6DA95'
light-magenta    = '#F5BDE6'
light-red        = '#ED8796'
light-white      = '#A5ADCB'
light-yellow     = '#EED49F'

tabs             = '#8AADF4'
tabs-active      = '#A6DA95'

