- name: Cronie - install
  ansible.builtin.package:
    name:
      - cronie

- name: Cronie - enable cronie server
  become: true
  ansible.builtin.service:
    name: cronie
    state: started
    enabled: true
