- name: Install microcode updates for intel (if necessary)
  ansible.builtin.package:
    name: intel-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
  when: system.processor == "intel"

- name: Install microcode updates for amd (if necessary)
  ansible.builtin.package:
    name: amd-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
  when: system.processor == "amd"
