- name: Ssh - install
  become: true
  become_user: true
  ansible.builtin.package:
    name:
      - openssh

- name: Ssh - enable and start service
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: started
