---
- name: File Manager - install packages
  become: true
  become_user: root
  ansible.builtin.package:
    update_cache: true
    name:
      - yazi
      - ffmpegthumbnailer
      - unarchiver
      - poppler
      - nemo
      - nemo-fileroller
      - nemo-image-converter
  notify:
    - Rkhunter propupdate
