# [desktop]
# wallpaper = "$HOME/dotfiles/wallpapers/sea.jpg"
# monitor = "HDMI-A-1"

[theme.fonts]
default = "SFMono Nerd Font"

[theme.colors]
yellow = "#f9e2af"
yellow_light = "#f5e0dc"

red = "#f38ba8"
red_light = "#eba0ac"

green = "#a6e3a1"
green_light = "#94e2d5"

blue = "#89b4fa"
blue_light = "#b4befe"

cyan = "#74c7ec"
magenta = "#cba6f7"

white = "#cdd6f4"
black = "#11111b"

gray_01 = "#bac2de"
gray_02 = "#a6adc8"
gray_03 = "#9399b2"
gray_04 = "#7f849c"
gray_05 = "#6c7086"
gray_06 = "#585b70"
gray_07 = "#45475a"
gray_08 = "#313244"
gray_09 = "#1e1e2e"
gray_10 = "#181825"

[theme.icons.volume]
zero = ""
low = ""
high = ""
muted = ""

[theme.icon.wifi]
low = ""
medium = ""
high = ""

[theme.icons.battery]
low = ""
medium = ""
high = ""
