[metadata]
name = "git-files"
description = "A channel to list the files currently tracked in the Git repository"
requirements = ["git", "bat"]

[source]
command = "git ls-files $(git rev-parse --show-toplevel)"

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
enter = "actions:edit"

[actions.edit]
description = "Open in nvim"
command = "nvim '{}'"
mode = "execute"
