- name: Terminals - install
  become: true
  ansible.builtin.package:
    name:
      - alacritty
      - wezterm
    state: present

- name: Alacritty
  ansible.builtin.import_tasks: ./config/alacritty.yml

- name: Wezterm
  ansible.builtin.import_tasks: ./config/wezterm.yml
