- name: Arch Linux Role
  hosts: local
  become: true
  block:
    - name: System
      include_tasks: ./arch/system/main.yml

    - name: Interface
      include_tasks: ./arch/interface/main.yml

    - name: Packages
      include_tasks: ./arch/packages/main.yml

