- name: Arch Roles
  hosts: local

  roles:
    - system-rkhunter
    - system-pacman
    - system-yay
    - system-user
    - system-grub
    - system-cronie
    - system-gpu
    - system-locale
    - system-time
    - system-ssh
    - system-network
    - system-bluetooth
    - system-audio

    - ui-hyprland
