- name: Audio - install dependencies
  ansible.builtin.package:
    name:
      - pipewire
      - pipewire-alsa
      - alsa-utils
      - pavucontrol
      - wireplumber

- name: Audio - pipewire service
  ansible.builtin.service:
    name: pipewire
    state: restarted
    enabled: "yes"

- name: Audio - WirePlumber service
  ansible.builtin.systemd:
    name: wireplumber
    state: restarted
    enabled: "yes"
