---
- name: 3D Apps - install
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - blender
      - qgis
    state: present

- name: 3D Apps - install aur packages
  kewlfft.aur.aur:
    use: yay
    name:
      - cura-bin
    state: present
  become: true
  become_user: aur_builder
